<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_asset_gallery_element' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Mon Mar 21 10:26:12 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfAssetsGalleryPlugin.lib.model
 */
class sfAssetGalleryElementPeer extends BasesfAssetGalleryElementPeer {

} // sfAssetGalleryElementPeer
